/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CourseMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "certificate"
      | "courseCount"
      | "courses"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "userCourses"
      | "web2ToCourseId"
      | "yiDengToken"
      | "addCourse"
      | "updateCourse"
      | "purchaseCourse"
      | "verifyCourseCompletion"
      | "batchVerifyCourseCompletion"
      | "hasCourse"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CourseAdded"
      | "CourseCompleted"
      | "CoursePurchased"
      | "CourseUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "certificate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "courseCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "courses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userCourses",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "web2ToCourseId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "yiDengToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addCourse",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCourse",
    values: [string, string, string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseCourse",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCourseCompletion",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "batchVerifyCourseCompletion",
    values: [AddressLike[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCourse",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "certificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "courseCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "courses", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCourses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "web2ToCourseId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yiDengToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addCourse", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCourseCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchVerifyCourseCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasCourse", data: BytesLike): Result;
}

export namespace CourseAddedEvent {
  export type InputTuple = [
    courseId: BigNumberish,
    web2CourseId: string,
    name: string
  ];
  export type OutputTuple = [
    courseId: bigint,
    web2CourseId: string,
    name: string
  ];
  export interface OutputObject {
    courseId: bigint;
    web2CourseId: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CourseCompletedEvent {
  export type InputTuple = [
    student: AddressLike,
    courseId: BigNumberish,
    certificateId: BigNumberish
  ];
  export type OutputTuple = [
    student: string,
    courseId: bigint,
    certificateId: bigint
  ];
  export interface OutputObject {
    student: string;
    courseId: bigint;
    certificateId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CoursePurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    courseId: BigNumberish,
    web2CourseId: string
  ];
  export type OutputTuple = [
    buyer: string,
    courseId: bigint,
    web2CourseId: string
  ];
  export interface OutputObject {
    buyer: string;
    courseId: bigint;
    web2CourseId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CourseUpdatedEvent {
  export type InputTuple = [
    courseId: BigNumberish,
    oldWeb2CourseId: string,
    newWeb2CourseId: string,
    name: string,
    price: BigNumberish,
    isActive: boolean
  ];
  export type OutputTuple = [
    courseId: bigint,
    oldWeb2CourseId: string,
    newWeb2CourseId: string,
    name: string,
    price: bigint,
    isActive: boolean
  ];
  export interface OutputObject {
    courseId: bigint;
    oldWeb2CourseId: string;
    newWeb2CourseId: string;
    name: string;
    price: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CourseMarket extends BaseContract {
  connect(runner?: ContractRunner | null): CourseMarket;
  waitForDeployment(): Promise<this>;

  interface: CourseMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  certificate: TypedContractMethod<[], [string], "view">;

  courseCount: TypedContractMethod<[], [bigint], "view">;

  courses: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, string] & {
        web2CourseId: string;
        name: string;
        price: bigint;
        isActive: boolean;
        creator: string;
      }
    ],
    "view"
  >;

  /**
   * Returns the address of the current owner.
   */
  owner: TypedContractMethod<[], [string], "view">;

  /**
   * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby disabling any functionality that is only available to the owner.
   */
  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  /**
   * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
   */
  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userCourses: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  web2ToCourseId: TypedContractMethod<[arg0: string], [bigint], "view">;

  yiDengToken: TypedContractMethod<[], [string], "view">;

  /**
   * 添加新课程到市场 只有合约所有者可以调用此函数
   * @param name 课程名称
   * @param price 课程价格(YD代币)
   * @param web2CourseId Web2平台的课程ID
   */
  addCourse: TypedContractMethod<
    [web2CourseId: string, name: string, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  /**
   * 修改课程 只有合约所有者可以调用此函数
   * @param name 课程名称
   * @param newWeb2CourseId 新的Web2平台的课程ID
   * @param oldWeb2CourseId 旧的Web2平台的课程ID
   * @param price 课程价格(YD代币)
   */
  updateCourse: TypedContractMethod<
    [
      oldWeb2CourseId: string,
      newWeb2CourseId: string,
      name: string,
      price: BigNumberish,
      isActive: boolean
    ],
    [void],
    "nonpayable"
  >;

  /**
   * 用户购买课程 用户需要先授权合约使用其YD代币
   * @param web2CourseId Web2平台的课程ID
   */
  purchaseCourse: TypedContractMethod<
    [web2CourseId: string],
    [void],
    "nonpayable"
  >;

  /**
   * 验证课程完成并发放证书 只有合约所有者可以调用此函数，确认学生已完成课程
   * @param student 学生地址
   * @param web2CourseId Web2平台的课程ID
   */
  verifyCourseCompletion: TypedContractMethod<
    [student: AddressLike, web2CourseId: string],
    [void],
    "nonpayable"
  >;

  /**
   * 批量验证课程完成 允许一次性为多个学生验证课程完成并发放证书
   * @param students 学生地址数组
   * @param web2CourseId Web2平台的课程ID
   */
  batchVerifyCourseCompletion: TypedContractMethod<
    [students: AddressLike[], web2CourseId: string],
    [void],
    "nonpayable"
  >;

  /**
   * 检查用户是否已购买课程
   * @param user 用户地址
   * @param web2CourseId Web2平台的课程ID
   */
  hasCourse: TypedContractMethod<
    [user: AddressLike, web2CourseId: string],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "certificate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "courseCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "courses"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, string] & {
        web2CourseId: string;
        name: string;
        price: bigint;
        isActive: boolean;
        creator: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userCourses"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "web2ToCourseId"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "yiDengToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addCourse"
  ): TypedContractMethod<
    [web2CourseId: string, name: string, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCourse"
  ): TypedContractMethod<
    [
      oldWeb2CourseId: string,
      newWeb2CourseId: string,
      name: string,
      price: BigNumberish,
      isActive: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "purchaseCourse"
  ): TypedContractMethod<[web2CourseId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyCourseCompletion"
  ): TypedContractMethod<
    [student: AddressLike, web2CourseId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchVerifyCourseCompletion"
  ): TypedContractMethod<
    [students: AddressLike[], web2CourseId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasCourse"
  ): TypedContractMethod<
    [user: AddressLike, web2CourseId: string],
    [boolean],
    "view"
  >;

  getEvent(
    key: "CourseAdded"
  ): TypedContractEvent<
    CourseAddedEvent.InputTuple,
    CourseAddedEvent.OutputTuple,
    CourseAddedEvent.OutputObject
  >;
  getEvent(
    key: "CourseCompleted"
  ): TypedContractEvent<
    CourseCompletedEvent.InputTuple,
    CourseCompletedEvent.OutputTuple,
    CourseCompletedEvent.OutputObject
  >;
  getEvent(
    key: "CoursePurchased"
  ): TypedContractEvent<
    CoursePurchasedEvent.InputTuple,
    CoursePurchasedEvent.OutputTuple,
    CoursePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "CourseUpdated"
  ): TypedContractEvent<
    CourseUpdatedEvent.InputTuple,
    CourseUpdatedEvent.OutputTuple,
    CourseUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CourseAdded(uint256,string,string)": TypedContractEvent<
      CourseAddedEvent.InputTuple,
      CourseAddedEvent.OutputTuple,
      CourseAddedEvent.OutputObject
    >;
    CourseAdded: TypedContractEvent<
      CourseAddedEvent.InputTuple,
      CourseAddedEvent.OutputTuple,
      CourseAddedEvent.OutputObject
    >;

    "CourseCompleted(address,uint256,uint256)": TypedContractEvent<
      CourseCompletedEvent.InputTuple,
      CourseCompletedEvent.OutputTuple,
      CourseCompletedEvent.OutputObject
    >;
    CourseCompleted: TypedContractEvent<
      CourseCompletedEvent.InputTuple,
      CourseCompletedEvent.OutputTuple,
      CourseCompletedEvent.OutputObject
    >;

    "CoursePurchased(address,uint256,string)": TypedContractEvent<
      CoursePurchasedEvent.InputTuple,
      CoursePurchasedEvent.OutputTuple,
      CoursePurchasedEvent.OutputObject
    >;
    CoursePurchased: TypedContractEvent<
      CoursePurchasedEvent.InputTuple,
      CoursePurchasedEvent.OutputTuple,
      CoursePurchasedEvent.OutputObject
    >;

    "CourseUpdated(uint256,string,string,string,uint256,bool)": TypedContractEvent<
      CourseUpdatedEvent.InputTuple,
      CourseUpdatedEvent.OutputTuple,
      CourseUpdatedEvent.OutputObject
    >;
    CourseUpdated: TypedContractEvent<
      CourseUpdatedEvent.InputTuple,
      CourseUpdatedEvent.OutputTuple,
      CourseUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
